# Generated by Django 4.2.7 on 2023-11-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('docente', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
